In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

In [7]:
#### One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[282, 324, 87, 429], [282, 324, 87, 8], [282, 251, 87, 7], [443, 268, 160, 392, 404], [443, 268, 160, 392, 114], [320, 282, 343, 87, 56], [487, 249, 340, 392]]


In [9]:
### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 282 324  87 429]
 [  0   0   0   0 282 324  87   8]
 [  0   0   0   0 282 251  87   7]
 [  0   0   0 443 268 160 392 404]
 [  0   0   0 443 268 160 392 114]
 [  0   0   0 320 282 343  87  56]
 [  0   0   0   0 487 249 340 392]]


In [13]:
## 10 feature dimesnions
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             5000      
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 282, 324,  87, 429])

In [17]:
model.predict(embedded_docs[0])

array([[[-0.00810255, -0.03118453, -0.0251568 ,  0.0075601 ,
         -0.04333271, -0.01470333, -0.04525594,  0.01695449,
          0.04141477, -0.00918848]],

       [[-0.00810255, -0.03118453, -0.0251568 ,  0.0075601 ,
         -0.04333271, -0.01470333, -0.04525594,  0.01695449,
          0.04141477, -0.00918848]],

       [[-0.00810255, -0.03118453, -0.0251568 ,  0.0075601 ,
         -0.04333271, -0.01470333, -0.04525594,  0.01695449,
          0.04141477, -0.00918848]],

       [[-0.00810255, -0.03118453, -0.0251568 ,  0.0075601 ,
         -0.04333271, -0.01470333, -0.04525594,  0.01695449,
          0.04141477, -0.00918848]],

       [[ 0.02843941,  0.04929235,  0.03066141, -0.03833275,
          0.03252672, -0.04172705, -0.0475989 , -0.02441927,
          0.01215122, -0.04054046]],

       [[-0.00086593, -0.02824146,  0.01637072,  0.01156379,
          0.02486664, -0.02524061, -0.02906298,  0.02207414,
         -0.04760392,  0.04868198]],

       [[-0.04476641, -0.0493319 , -0.03

In [18]:
print(model.predict(embedded_docs))

[[[-0.00810255 -0.03118453 -0.0251568   0.0075601  -0.04333271
   -0.01470333 -0.04525594  0.01695449  0.04141477 -0.00918848]
  [-0.00810255 -0.03118453 -0.0251568   0.0075601  -0.04333271
   -0.01470333 -0.04525594  0.01695449  0.04141477 -0.00918848]
  [-0.00810255 -0.03118453 -0.0251568   0.0075601  -0.04333271
   -0.01470333 -0.04525594  0.01695449  0.04141477 -0.00918848]
  [-0.00810255 -0.03118453 -0.0251568   0.0075601  -0.04333271
   -0.01470333 -0.04525594  0.01695449  0.04141477 -0.00918848]
  [ 0.02843941  0.04929235  0.03066141 -0.03833275  0.03252672
   -0.04172705 -0.0475989  -0.02441927  0.01215122 -0.04054046]
  [-0.00086593 -0.02824146  0.01637072  0.01156379  0.02486664
   -0.02524061 -0.02906298  0.02207414 -0.04760392  0.04868198]
  [-0.04476641 -0.0493319  -0.03429061  0.03083891 -0.04799788
    0.01912143 -0.03994465  0.01431218  0.03893818  0.00405564]
  [ 0.00939692  0.04483316 -0.02274296 -0.04999394  0.03132461
   -0.00461543 -0.045451    0.00561516 -0.027532

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 282, 324,  87, 429])

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]